import { readFile, writeFile } from 'node:fs/promises';

const srcPath = new URL('../src/window/names.json', import.meta.url);
const outPath = new URL('../src/window/names.ts', import.meta.url);

type NamesJson = {
  version?: unknown;
  adjectives?: unknown;
  nouns?: unknown;
};

const parsed = JSON.parse(await readFile(srcPath, 'utf8')) as NamesJson;
const version = typeof parsed.version === 'number' ? parsed.version : 1;
const adjectives = Array.isArray(parsed.adjectives) ? parsed.adjectives.filter((x): x is string => typeof x === 'string') : [];
const nouns = Array.isArray(parsed.nouns) ? parsed.nouns.filter((x): x is string => typeof x === 'string') : [];

const contents = [
  '// This file is generated by scripts/sync-window-names.ts.',
  `export const WINDOW_NAMES_VERSION = ${JSON.stringify(version)} as const;`,
  `export const WINDOW_ADJECTIVES = ${JSON.stringify(adjectives, null, 2)} as const;`,
  `export const WINDOW_NOUNS = ${JSON.stringify(nouns, null, 2)} as const;`,
  '',
].join('\n');

await writeFile(outPath, contents, 'utf8');
