import { readFile, writeFile } from 'node:fs/promises';

const pkgPath = new URL('../package.json', import.meta.url);
const outPath = new URL('../src/version.ts', import.meta.url);

type PackageJson = { version?: unknown };

const pkg = JSON.parse(await readFile(pkgPath, 'utf8')) as PackageJson;
const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';

const contents = [
  '// This file is generated by scripts/sync-version.ts.',
  `export const LIQUID_MAIL_VERSION = ${JSON.stringify(version)};`,
  '',
].join('\n');

await writeFile(outPath, contents, 'utf8');
